# Generated by Django 4.2.30 on 2026-04-27 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(help_text='Contenido simulado del documento (enunciado).')),
                ('pipeline_config', models.JSONField(help_text='Qué etapas ejecutar, p. ej. extract, analyze, enrich.')),
                ('partial_results', models.JSONField(blank=True, help_text='Resultados por etapa completada (preservar ante fallo posterior).', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
