# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import job_gateway_pb2 as job__gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentProcessingGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/jobgateway.DocumentProcessingGateway/CreateJob',
                request_serializer=job__gateway__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=job__gateway__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/jobgateway.DocumentProcessingGateway/GetJob',
                request_serializer=job__gateway__pb2.GetJobRequest.SerializeToString,
                response_deserializer=job__gateway__pb2.JobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/jobgateway.DocumentProcessingGateway/ListJobs',
                request_serializer=job__gateway__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=job__gateway__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/jobgateway.DocumentProcessingGateway/CancelJob',
                request_serializer=job__gateway__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=job__gateway__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class DocumentProcessingGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentProcessingGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=job__gateway__pb2.CreateJobRequest.FromString,
                    response_serializer=job__gateway__pb2.JobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=job__gateway__pb2.GetJobRequest.FromString,
                    response_serializer=job__gateway__pb2.JobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=job__gateway__pb2.ListJobsRequest.FromString,
                    response_serializer=job__gateway__pb2.ListJobsResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=job__gateway__pb2.CancelJobRequest.FromString,
                    response_serializer=job__gateway__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobgateway.DocumentProcessingGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobgateway.DocumentProcessingGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentProcessingGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobgateway.DocumentProcessingGateway/CreateJob',
            job__gateway__pb2.CreateJobRequest.SerializeToString,
            job__gateway__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobgateway.DocumentProcessingGateway/GetJob',
            job__gateway__pb2.GetJobRequest.SerializeToString,
            job__gateway__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobgateway.DocumentProcessingGateway/ListJobs',
            job__gateway__pb2.ListJobsRequest.SerializeToString,
            job__gateway__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobgateway.DocumentProcessingGateway/CancelJob',
            job__gateway__pb2.CancelJobRequest.SerializeToString,
            job__gateway__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
