# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11job_gateway.proto\x12\njobgateway\"\xa9\x01\n\x0ePipelineConfig\x12\x0e\n\x06stages\x18\x01 \x03(\t\x12M\n\x12provider_overrides\x18\x02 \x03(\x0b\x32\x31.jobgateway.PipelineConfig.ProviderOverridesEntry\x1a\x38\n\x16ProviderOverridesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x86\x01\n\x10\x43reateJobRequest\x12\x15\n\rdocument_name\x18\x01 \x01(\t\x12\x15\n\rdocument_type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x33\n\x0fpipeline_config\x18\x04 \x01(\x0b\x32\x1a.jobgateway.PipelineConfig\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"!\n\x0fListJobsRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x10ListJobsResponse\x12%\n\x04jobs\x18\x01 \x03(\x0b\x32\x17.jobgateway.JobResponse\"\"\n\x10\x43\x61ncelJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"U\n\x11\x43\x61ncelJobResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12$\n\x03job\x18\x02 \x01(\x0b\x32\x17.jobgateway.JobResponse\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\xe7\x01\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rdocument_name\x18\x03 \x01(\t\x12\x15\n\rdocument_type\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x1c\n\x14pipeline_config_json\x18\x06 \x01(\t\x12\x1c\n\x14partial_results_json\x18\x07 \x01(\t\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t2\xae\x02\n\x19\x44ocumentProcessingGateway\x12\x42\n\tCreateJob\x12\x1c.jobgateway.CreateJobRequest\x1a\x17.jobgateway.JobResponse\x12<\n\x06GetJob\x12\x19.jobgateway.GetJobRequest\x1a\x17.jobgateway.JobResponse\x12\x45\n\x08ListJobs\x12\x1b.jobgateway.ListJobsRequest\x1a\x1c.jobgateway.ListJobsResponse\x12H\n\tCancelJob\x12\x1c.jobgateway.CancelJobRequest\x1a\x1d.jobgateway.CancelJobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINECONFIG_PROVIDEROVERRIDESENTRY']._loaded_options = None
  _globals['_PIPELINECONFIG_PROVIDEROVERRIDESENTRY']._serialized_options = b'8\001'
  _globals['_PIPELINECONFIG']._serialized_start=34
  _globals['_PIPELINECONFIG']._serialized_end=203
  _globals['_PIPELINECONFIG_PROVIDEROVERRIDESENTRY']._serialized_start=147
  _globals['_PIPELINECONFIG_PROVIDEROVERRIDESENTRY']._serialized_end=203
  _globals['_CREATEJOBREQUEST']._serialized_start=206
  _globals['_CREATEJOBREQUEST']._serialized_end=340
  _globals['_GETJOBREQUEST']._serialized_start=342
  _globals['_GETJOBREQUEST']._serialized_end=373
  _globals['_LISTJOBSREQUEST']._serialized_start=375
  _globals['_LISTJOBSREQUEST']._serialized_end=408
  _globals['_LISTJOBSRESPONSE']._serialized_start=410
  _globals['_LISTJOBSRESPONSE']._serialized_end=467
  _globals['_CANCELJOBREQUEST']._serialized_start=469
  _globals['_CANCELJOBREQUEST']._serialized_end=503
  _globals['_CANCELJOBRESPONSE']._serialized_start=505
  _globals['_CANCELJOBRESPONSE']._serialized_end=590
  _globals['_JOBRESPONSE']._serialized_start=593
  _globals['_JOBRESPONSE']._serialized_end=824
  _globals['_DOCUMENTPROCESSINGGATEWAY']._serialized_start=827
  _globals['_DOCUMENTPROCESSINGGATEWAY']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
